# Generated by Django 5.2.6 on 2025-10-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_auth',
            field=models.CharField(default='', null=True),
        ),
    ]
